version: '3'
services:

   node-red:
    image: burnsys/nodered:pi
    container_name: node-red
    environment:
       - TZ=America/Argentina/Buenos_Aires
       - LD_LIBRARY_PATH=/opt/vc/lib
    ports:
       - 1880:1880
    devices:
       - /dev/vchiq
    user: root:root
    volumes:
       - /home/pi/HomeAutomation/Docker/nodered-data:/data
       - /opt/vc:/opt/vc:ro
    restart: unless-stopped
    deploy:
      placement:
        constraints:
          - "node.hostname==RPI4"