version: '3'
services:

 cloudflare:
      image: oznu/cloudflare-ddns:armhf
      container_name: cloudflare
      restart: always
      environment:
        - API_KEY=O3P9F6FkCDeGrP0N7djFyCXoQf8h3UflfuC1Z1Yg
        - ZONE=burnsys.net.ar
        - PROXIED=true