version: '3'
services:

  cloudflare:
      image: oznu/cloudflare-ddns:armhf
      container_name: cloudflare
      restart: always
      environment:
        - API_KEY=O3P9F6FkCDeGrP0N7djFyCXoQf8h3UflfuC1Z1Yg
        - ZONE=burnsys.net.ar
        - PROXIED=true

  samba:
    image: dperson/samba:rpi
    container_name: samba
    mode: global
    command: '-p -u "pi;Jst4kix741" -s "home;/home;yes;no;no"'
    stdin_open: true
    tty: true
    ports:
      - 139:139
      - 445:445
    volumes:
      - /home:/home
    restart: always