version: '3'
services:

  maria-db:
    image: jsurf/rpi-mariadb
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=AdMiNiStRaToR25082021
      - MYSQL_DATABASE=npm
      - MYSQL_USER=npm
      - MYSQL_PASSWORD=npm
    volumes:
      - ../../../../mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    deploy:
      placement:
        constraints:
          - node.hostname == RPI4
      mode: replicated
      replicas: 1
    restart: unless-stopped
    
  nginx-proxy:
    image: jc21/nginx-proxy-manager
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
      - 81:81
    volumes:
      - ../../nginx-proxy/data:/data
      - ../../nginx-proxy/letsencrypt:/etc/letsencrypt
    environment:
      DB_MYSQL_HOST: "maria-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    deploy:
      placement:
        constraints:
          - node.hostname == RPI4
      mode: replicated
      replicas: 1
    depends_on:
      - maria-db
